version: "3"

services:
  #######################################
  # Keycloak: The IAM
  #######################################
  keycloak:
    image: "jboss/keycloak:latest"
    restart: on-failure
    env_file: config/keycloak.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"

  #######################################
  # Configure Keycloak
  #######################################
  keycloak-config:
    image: "jboss/keycloak:latest"
    restart: on-failure
    entrypoint: "/bin/bash -c /configure-keycloak.sh"
    env_file: config/keycloak.env
    volumes:
      - ./config/configure-keycloak.sh:/configure-keycloak.sh

